# SPDX-License-Identifier: LGPL-2.1-or-later
# SPDX-FileCopyrightText: Copyright 2026 Yun Chan

param(
    [string]$SourcePath = (Join-Path $env:TEMP "nikl-korean-learning-vocab.txt"),
    [string]$OutputPath = (Join-Path $PSScriptRoot "..\plugin\hangul\src\main\cpp\fcitx5-hangul\data\completion.txt")
)

$ErrorActionPreference = "Stop"

$sourceUrl = "https://www.korean.go.kr/common/download.do?c_file_name=b73a8438-4713-4436-8481-ec26fd0dce2a_0.txt&file_path=etcData&o_file_name=%ED%95%9C%EA%B5%AD%EC%96%B4+%ED%95%99%EC%8A%B5%EC%9A%A9+%EC%96%B4%ED%9C%98+%EB%AA%A9%EB%A1%9D.txt"
$expectedSha256 = "3B49681F05D6A7490C13DA2A2847E433EFFDF65DA409FD295792D6EE33685064"

if (-not (Test-Path -LiteralPath $SourcePath)) {
    Invoke-WebRequest -Uri $sourceUrl -OutFile $SourcePath
}

$actualSha256 = (Get-FileHash -LiteralPath $SourcePath -Algorithm SHA256).Hash
if ($actualSha256 -ne $expectedSha256) {
    throw "Unexpected source checksum: $actualSha256"
}

# Project-authored mobile conversation forms. These intentionally precede the
# source frequency list because the source contains dictionary headwords rather
# than many forms people actually finish in chat.
$curatedWords = @(
    "안녕하세요", "안녕하십니까", "안녕히가세요", "안녕히계세요",
    "감사합니다", "감사드립니다", "감사해요", "고맙습니다", "고마워요",
    "죄송합니다", "죄송해요", "미안합니다", "미안해요",
    "괜찮습니다", "괜찮아요", "괜찮으세요", "알겠습니다", "알겠어요",
    "확인했습니다", "확인했어요", "확인해주세요", "확인부탁드립니다",
    "부탁드립니다", "부탁드리겠습니다", "수고하셨습니다", "수고하세요",
    "고생하셨습니다", "고생하세요", "축하합니다", "축하드립니다",
    "잘부탁드립니다", "잘부탁드리겠습니다", "잘지내세요", "잘자요",
    "좋은아침입니다", "좋은하루보내세요", "좋은주말보내세요",
    "다녀오겠습니다", "다녀오세요", "다녀왔습니다", "어서오세요",
    "반갑습니다", "반가워요", "오랜만입니다", "오랜만이에요",
    "가능합니다", "가능해요", "불가능합니다", "어렵습니다", "어려워요",
    "맞습니다", "맞아요", "아닙니다", "아니에요", "그렇습니다", "그래요",
    "좋습니다", "좋아요", "싫습니다", "싫어요", "재미있습니다", "재미있어요",
    "보고싶어요", "사랑합니다", "사랑해요", "행복하세요", "건강하세요",
    "도와주세요", "알려주세요", "말씀해주세요", "연락주세요", "전화주세요",
    "기다려주세요", "잠시만요", "잠시후에", "조금이따가", "나중에봐요",
    "지금출발합니다", "곧도착합니다", "도착했습니다", "출발했습니다",
    "늦어서죄송합니다", "답장이늦어서죄송합니다", "확인이늦었습니다",
    "오늘가능합니다", "내일가능합니다", "이번주가능합니다",
    "언제가능하세요", "몇시가좋으세요", "어디로가면될까요",
    "회의중입니다", "통화중입니다", "운전중입니다", "업무중입니다",
    "식사하셨어요", "맛있게드세요", "잘먹겠습니다", "잘먹었습니다",
    "보내드렸습니다", "전달드렸습니다", "공유드립니다", "첨부드립니다",
    "검토부탁드립니다", "회신부탁드립니다", "참고부탁드립니다",
    "문의드립니다", "답변드립니다", "안내드립니다", "말씀드립니다"
)

$sourceBytes = [System.IO.File]::ReadAllBytes((Resolve-Path -LiteralPath $SourcePath))
$sourceText = [System.Text.Encoding]::GetEncoding(949).GetString($sourceBytes)
$sourceRows = $sourceText | ConvertFrom-Csv -Delimiter "`t"

$rankedSourceWords = foreach ($row in $sourceRows) {
    $rank = 0
    if (-not [int]::TryParse($row.'순위', [ref]$rank)) {
        continue
    }
    $word = ($row.'단어' -replace '\d{2}$', '').Trim()
    if ($word -notmatch '^[가-힣]{2,}$') {
        continue
    }
    [pscustomobject]@{ Rank = $rank; Word = $word }
}

$rankedSourceWords = $rankedSourceWords | Sort-Object Rank, Word
$seen = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
$orderedWords = [System.Collections.Generic.List[string]]::new()

foreach ($word in $curatedWords) {
    if ($seen.Add($word)) {
        $orderedWords.Add($word)
    }
}
foreach ($entry in $rankedSourceWords) {
    if ($seen.Add($entry.Word)) {
        $orderedWords.Add($entry.Word)
    }
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("# Generated by scripts/generate-korean-completion-dictionary.ps1")
$lines.Add("# Source: National Institute of Korean Language, Korean learning vocabulary list")
$lines.Add("# Source SHA-256: $expectedSha256")
$lines.Add("# License: Korea Open Government License Type 1 (attribution)")
$lines.Add("# Format: display priority<TAB>word; lower priority sorts first")
for ($index = 0; $index -lt $orderedWords.Count; $index++) {
    $lines.Add(('{0:D6}' -f ($index + 1)) + "`t" + $orderedWords[$index])
}

$resolvedOutput = [System.IO.Path]::GetFullPath($OutputPath)
[System.IO.File]::WriteAllLines(
    $resolvedOutput,
    $lines,
    [System.Text.UTF8Encoding]::new($false)
)

Write-Output "Wrote $($orderedWords.Count) unique words to $resolvedOutput"
